title: Jay's Homepage
author: Jay Menon
email: menonjay85@gmail.com
description: >-
  I am a Robotics Engineer at ASU.

social:
  twitter: menonjay85
  facebook: menonjay85
  instagram: menonjay85
  github: menonjay85
  linkedin: menonjay85

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  images:
    output: true
